require('dotenv').config();
const TokenCollector = require('./index.js');
const fs = require('fs').promises;
const path = require('path');

class DailyAudit {
  constructor() {
    this.collector = new TokenCollector();
    this.reportDir = path.join(__dirname, 'reports');
  }

  async generateDailyReport() {
    try {
      await fs.mkdir(this.reportDir, { recursive: true });
      
      const today = new Date().toISOString().split('T')[0];
      const reportFile = path.join(this.reportDir, `audit-${today}.json`);
      const reportTextFile = path.join(this.reportDir, `audit-${today}.md`);
      
      // Load current data
      await this.collector.loadExistingData();
      const data = this.collector.getLatestData();
      
      // Calculate daily statistics
      const todayUsage = data.tokenUsage.daily[today] || { tokensIn: 0, tokensOut: 0, context: 0 };
      const totalUsage = data.tokenUsage.total;
      
      const report = {
        date: today,
        timestamp: new Date().toISOString(),
        daily: todayUsage,
        total: totalUsage,
        agents: data.agents,
        channels: data.channels,
        tools: data.tools,
        sessionCount: data.sessions.length,
        summary: {
          dailyTotal: todayUsage.tokensIn + todayUsage.tokensOut + todayUsage.context,
          totalTokens: totalUsage.tokensIn + totalUsage.tokensOut + totalUsage.context,
          averageTokensPerSession: data.sessions.length > 0 
            ? Math.round((totalUsage.tokensIn + totalUsage.tokensOut + totalUsage.context) / data.sessions.length)
            : 0,
          topAgent: this.getTopItem(data.agents),
          topChannel: this.getTopItem(data.channels),
          topTool: this.getTopItem(data.tools)
        }
      };
      
      // Save JSON report
      await fs.writeFile(reportFile, JSON.stringify(report, null, 2));
      
      // Generate markdown report
      const markdownReport = this.generateMarkdownReport(report);
      await fs.writeFile(reportTextFile, markdownReport);
      
      console.log(`📊 Daily audit report generated:`);
      console.log(`   JSON: ${reportFile}`);
      console.log(`   Markdown: ${reportTextFile}`);
      console.log(`   Daily tokens: ${report.summary.dailyTotal}`);
      console.log(`   Total tokens: ${report.summary.totalTokens}`);
      
      return report;
      
    } catch (error) {
      console.error('❌ Daily audit failed:', error.message);
      throw error;
    }
  }

  getTopItem(items) {
    if (!items || Object.keys(items).length === 0) return 'None';
    
    return Object.entries(items)
      .sort(([,a], [,b]) => b - a)[0]?.[0] || 'None';
  }

  generateMarkdownReport(report) {
    return `# 🌸 Daily Token Audit Report

**Date**: ${report.date}  
**Generated**: ${new Date(report.timestamp).toLocaleString()}

## 📊 Token Usage Summary

### Today's Usage
- **Tokens In**: ${report.daily.tokensIn.toLocaleString()}
- **Tokens Out**: ${report.daily.tokensOut.toLocaleString()}
- **Context**: ${report.daily.context.toLocaleString()}
- **Daily Total**: ${report.summary.dailyTotal.toLocaleString()}

### Cumulative Usage
- **Total Tokens In**: ${report.total.tokensIn.toLocaleString()}
- **Total Tokens Out**: ${report.total.tokensOut.toLocaleString()}
- **Total Context**: ${report.total.context.toLocaleString()}
- **Grand Total**: ${report.summary.totalTokens.toLocaleString()}

## 🎯 Usage Analytics

- **Total Sessions**: ${report.sessionCount}
- **Average Tokens/Session**: ${report.summary.averageTokensPerSession}
- **Top Agent**: ${report.summary.topAgent}
- **Top Channel**: ${report.summary.topChannel}
- **Top Tool**: ${report.summary.topTool}

## 🤖 Agent Usage
${this.formatUsageTable(report.agents)}

## 📡 Channel Usage
${this.formatUsageTable(report.channels)}

## 🛠️ Tool Usage
${this.formatUsageTable(report.tools)}

---
*Generated by OpenClaw Token Audit System 🌸*
`;
  }

  formatUsageTable(usage) {
    if (!usage || Object.keys(usage).length === 0) {
      return '*(No usage data)*';
    }
    
    const entries = Object.entries(usage)
      .sort(([,a], [,b]) => b - a)
      .slice(0, 10); // Top 10
    
    let table = '| Item | Count |\n|------|-------|\n';
    entries.forEach(([item, count]) => {
      table += `| ${item} | ${count} |\n`;
    });
    
    return table;
  }

  async runWeeklyAnalysis() {
    try {
      const historicalData = await this.collector.getHistoricalData(7);
      
      const weeklyReport = {
        period: 'Last 7 days',
        data: historicalData,
        summary: {
          totalDays: historicalData.length,
          averageDaily: this.calculateWeeklyAverages(historicalData)
        }
      };
      
      const reportFile = path.join(this.reportDir, `weekly-${new Date().toISOString().split('T')[0]}.json`);
      await fs.writeFile(reportFile, JSON.stringify(weeklyReport, null, 2));
      
      console.log(`📈 Weekly analysis saved to: ${reportFile}`);
      return weeklyReport;
      
    } catch (error) {
      console.error('❌ Weekly analysis failed:', error.message);
      throw error;
    }
  }

  calculateWeeklyAverages(data) {
    if (data.length === 0) return { tokensIn: 0, tokensOut: 0, context: 0 };
    
    const totals = data.reduce(
      (acc, day) => ({
        tokensIn: acc.tokensIn + (day.tokenUsage?.tokensIn || 0),
        tokensOut: acc.tokensOut + (day.tokenUsage?.tokensOut || 0),
        context: acc.context + (day.tokenUsage?.context || 0)
      }),
      { tokensIn: 0, tokensOut: 0, context: 0 }
    );
    
    return {
      tokensIn: Math.round(totals.tokensIn / data.length),
      tokensOut: Math.round(totals.tokensOut / data.length),
      context: Math.round(totals.context / data.length)
    };
  }
}

async function main() {
  const audit = new DailyAudit();
  
  try {
    const dailyReport = await audit.generateDailyReport();
    console.log('✅ Daily audit completed successfully');
    
    // Run weekly analysis if it's Sunday
    if (new Date().getDay() === 0) {
      await audit.runWeeklyAnalysis();
      console.log('✅ Weekly analysis completed');
    }
    
  } catch (error) {
    console.error('❌ Audit process failed:', error.message);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = DailyAudit;